on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Tag release
    steps:
      - name: Create and release a tag
        id: hello
        uses: 9bany/create-tag-to-another-action@v1.0-rc13
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          owner: 9bany
          reponame: create-tag-to-another-action-example
          tag: v1.0.2
          message: v1.0.2
          name: 9bany
          email: bany.y0599@gmail.com
          branch: master